apiVersion: v1
kind: ConfigMap
metadata:
  name: kubewatch-config
  namespace: kube-system
data:
  config.yaml: |
    handler:
      team:
        webhook: "https://outlook.office.com/webhook/YOUR_TEAMS_WEBHOOK_URL"
    namespace:
      include:
        - default
    resource:
      pod: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubewatch
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubewatch
  namespace: kube-system
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubewatch
  namespace: kube-system
subjects:
  - kind: ServiceAccount
    name: kubewatch
    namespace: kube-system
roleRef:
  kind: Role
  name: kubewatch
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubewatch
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubewatch
  template:
    metadata:
      labels:
        app: kubewatch
    spec:
      serviceAccountName: kubewatch
      containers:
        - name: kubewatch
          image: robustadev/kubewatch:v2.6
          env:
            - name: KW_CONFIG
              value: /config/config.yaml
          volumeMounts:
            - name: config-volume
              mountPath: /config
              subPath: config.yaml
      volumes:
        - name: config-volume
          configMap:
            name: kubewatch-config
            items:
              - key: config.yaml
                path: config.yaml

